<?php

require_once __DIR__ . '/../controllers/BaseController.php';

use PHPUnit\Framework\TestCase;

class BaseControllerTest extends TestCase
{
    public function test_save_file_creates_directories()
    {
        $uploaded_file_array = [
            'full_path' => 'foo.txt',
            'name' => 'foo.txt',
            'tmp_name' => dirname(__FILE__) . "/resources/foo.txt",
        ];

        $path = (new TestableController())->saveFile($uploaded_file_array, "foo");

        $this->assertDirectoryExists(dirname(__FILE__) . "/../storage/foo/");
    }


    public function test_save_file_writes_the_test_to_disk()
    {
        $uploaded_file_array = [
            'full_path' => 'foo.txt',
            'name' => 'foo.txt',
            'tmp_name' => dirname(__FILE__) . "/resources/foo.txt",
        ];

        $path = (new TestableController())->saveFile($uploaded_file_array, "foo");

        $this->markTestIncomplete("Techdebt: we should provide an OOP abstraction layer for an uploaded file, such that we can mock it in tests.");

        $this->assertEqual("bar", file_get_contents($path));
    }
}

class TestableController extends BaseController
{

    public function run(): mixed
    {
        return "foo";
    }

    protected function shouldRun(): bool
    {
        return true;
    }

    public function saveFile(array $uploaded_file_array, string $storage_path): string|bool
    {
        return parent::saveFile($uploaded_file_array, $storage_path); // TODO: Change the autogenerated stub
    }
}